### ISSUE TITLE
Hopper not loading CPU

### ISSUE THREAD

**Issue by hezi** [mypasswordisqwerty/HopperDos#9]
I keep getting this message in console when trying to load Inter16CPU.hopperCPU

```
  ERROR: Cannot load /Users/hezi/Library/Application Support/Hopper/PlugIns/v4/CPUs/Intel16CPU.hopperCPU, plugin makes use of external function(s), and may be too slow for a CPU plugin. Also, make sure that plugin is compiled for OS X 10.9, or higher.
  error: Plugin imports dylib /usr/local/lib/libcapstone.dylib
```

Any ideas why?

**Comment by mypasswordisqwerty** [comment]
CPU interface was changed in newer Hopper version. Plugin code already updated, but not released yet.

**Comment by mypasswordisqwerty** [comment]
But now I understand that you have another problem. You are building plugin with capstone(brew?) dynamic library. Hopper doesn't allow dynamic libraries in CPU plugins (performance issues). You must build static capstone library from source.
